### ISSUE TITLE
plugin.video.mediapoisk, plugin.video.okino

### ISSUE THREAD

**Issue by xbmcrepo** [anteo/xbmc.repository#1]
Антон,
Лог ошибок plugin.video.mediapoisk, plugin.video.okino здесь
http://paste.ubuntu.com/12397421/

plugin.video.okino в свою очередь видимо не может достучаться до Нидерландского сервера, ошибка - истекло время ожидания отклика от сервера. Или для обоих плагинов требуется быть клиентом какого-то определённого провайдера? Что такое расширенные настроки провайдера, упомянутые в описании плагина?

plugin.video.lostfilm.tv - без проблем
p.s.
Антон, Ваш xbmc.repository добавлен в seppius-xbmc-repo/ru 
https://github.com/seppius-xbmc-repo/ru -
это клон исходного https://code.google.com/p/seppius-xbmc-repo/source/browse/
Плагин repository.search.db 
https://github.com/seppius-xbmc-repo/ru/tree/master/repository.search.db
сканирует базы данных репо(Git) авторов плагинов русского форума 
http://xbmc.ru/forum/
и выводит в категориях .
Если Вы против включения Вашего xbmc.repository в поисковик, то сообщите мне 
xbmc@inbox.ru
Или в личном сообщении http://xbmc.ru/forum/ пользовaтель bigbax
http://xbmc.ru/forum/member.php?u=22

**Comment by anteo** [comment]
Да, это плагины разработанные специально для провайдера и работают только у него. Вернее уже не работают, через некоторое время я вообще исключу их из репозитория, если ситуация не изменится.

Плагин для LostFilm.TV рабочий, но еще совсем новый, в скором времени я добавлю весь планируемый функционал, сделаю описание и анонс на xbmc.ru

Я не против включения моего репозитория в поисковик, наоборот, это дело нужное, особенно когда готовый плагин нужно будет анонсировать сообществу. Так что спасибо!

**Comment by xbmcrepo** [comment]
Антон!
Спасибо за ответ. LostFilm.tv -мне очень понравился.
Аддоны, которые работают с випами или просто заточенные под определённого провайдера, если работают, то "убивать" не стоит - найдут своего пользователя.
Как пример kinozal.tv, Torrent.TV -платные, но люди подписываются. Не везде есть региональное вещание или скажем деньги на спутник.

>Вторник, 15 сентября 2015, 4:52 -07:00 от Anton Argirov <notifications@github.com>:
>
>Да, это плагины разработанные специально для провайдера и работают только у него. Вернее уже не работают, через некоторое время я вообще исключу их из репозитория, если ситуация не изменится.
>Плагин для LostFilm.TV рабочий, но еще совсем новый, в скором времени я добавлю весь планируемый функционал, сделаю описание и анонс на xbmc.ru
>Я не против включения моего репозитория в поисковик, наоборот, это дело нужное, особенно когда готовый плагин нужно будет анонсировать сообществу. Так что спасибо!
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax

**Comment by anteo** [comment]
Ну, в моем случае, сервис, похоже, окончательно умер (я имею ввиду окино.ру и медиапоиск), так что код пойдет на разработку новых плагинов

**Comment by xbmcrepo** [comment]
Антон!
Если убрать plugin.video.mediapoisk, plugin.video.okino из   https://github.com/anteo/xbmc.repository , оставив при этом их 
в  https://github.com/anteo/plugin.video.okino  и в  https://github.com/anteo/plugin.video.mediapoisk  , то в repository.search.db они не будут видны, так как он берёт инфо о плагинах из Вашего xbmc.repository.
Будете когда будете убирать эти два плагина, не забудьте обновить в xbmc.repository  addons.xml.md5  и addons.xml



>Вторник, 15 сентября 2015, 9:33 -07:00 от Anton Argirov <notifications@github.com>:
>
>Ну, в моем случае, сервис, похоже, окончательно умер (я имею ввиду окино.ру и медиапоиск), так что код пойдет на разработку новых плагинов
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax

**Comment by xbmcrepo** [comment]
http://addons.tvaddons.ag/category/international/russian/
хорошая компания собралась


>Пятница, 16 октября 2015, 2:14 -07:00 от Anton Argirov <notifications@github.com>:
>
>Closed  #1 .
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax

**Comment by xbmcrepo** [comment]
упс, мои три поисковика тоже, правда в самом конце списка
http://addons.tvaddons.ag/category/international/russian/?page=2


>Пятница, 16 октября 2015, 2:14 -07:00 от Anton Argirov <notifications@github.com>:
>
>Closed  #1 .
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax
