### ISSUE TITLE
Lost film tv 

### ISSUE THREAD

**Issue by xbmcrepo** [anteo/xbmc.repository#2]
1) Системы OpenElec_NVidia Legacy  и андроид Kodi 15.1 , Kodi 15.2.
Даю лог ошибки
http://paste.ubuntu.com/12694762/

2) Ещё одно замечание, в зависимостях плагина указано, но нет в в Вашем Git xbmc.repository
 addon="script.module.requests" version="2.7.0"/
https://github.com/beenje/script.module.requests

**Comment by anteo** [comment]
1) Сделал фикс (версия 0.0.4, должна обновиться сама). Вообще, не думал, что уже кто-то пользуется, версию сразу после поломки не выпускал :)
2) Вроде script.module.requests в стандартном репозитории (repository.xbmc.org) живет, так что везде должен быть доступен. Ряд других плагинов уже с давних пор используют данный аддон, так что никаких проблем не должно быть

**Comment by xbmcrepo** [comment]
Да, но версия 1.1.0

> Понедельник,  5 октября 2015, 21:32 -07:00 от Anton Argirov <notifications@github.com>:
> 
> 
> 1) Сделал фикс (версия 0.0.4, должна обновиться сама). Вообще, не думал, что уже кто-то пользуется, версию сразу после поломки не выпускал :)
> 2) Вроде script.module.requests в стандартном репозитории (repository.xbmc.org) живет, так что везде должен быть доступен. Ряд других плагинов уже с давних пор используют данный аддон, так что никаких проблем не должно быть
> —
> Reply to this email directly or  view it on GitHub .
> 

С уважением,
Владимир
-- 
bigbax

**Comment by anteo** [comment]
Только что проверил, 
http://mirror.yandex.ru/mirrors/xbmc/addons/gotham/addons.xml
```xml
<addon id="script.module.requests" name="requests" provider-name="kennethreitz, beenje" version="2.7.0">
```

**Comment by xbmcrepo** [comment]
Антон!
Это проблемы в андроид и ОпенЭлек. На убунте обновил до версии  0.4 и в ней заработало.

А в андроиде и опенэлеке в 0.4 канючит с авторизацией и не соединяется с сервером 
Но это скорее всего даже проблема с айсстрим, либо script.module.torrent2http/
Вечером в логи посмотрю что там не так


>Понедельник,  5 октября 2015, 21:44 -07:00 от Anton Argirov <notifications@github.com>:
>
>Только что проверил, 
>http://mirror.yandex.ru/mirrors/xbmc/addons/gotham/addons.xml
><addon id="script.module.requests" name="requests" provider-name="kennethreitz, beenje" version="2.7.0">
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax

**Comment by xbmcrepo** [comment]
в дополнение к предыдущему :
06:56:52 T:1709955544  NOTICE: [support.abstract.scraper] Parsing episodes list started...
06:56:52 T:1709955544  NOTICE: [support.abstract.scraper] Parsing episodes list taken: 0.219887 seconds
06:56:52 T:1709955544   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<-- похоже в андроид , да и наверное в опенэлеке на этом скрапере спотыкается.
Сейчас на работе. Логи вечером посмотрю


>Понедельник,  5 октября 2015, 21:44 -07:00 от Anton Argirov <notifications@github.com>:
>
>Только что проверил, 
>http://mirror.yandex.ru/mirrors/xbmc/addons/gotham/addons.xml
><addon id="script.module.requests" name="requests" provider-name="kennethreitz, beenje" version="2.7.0">
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax

**Comment by anteo** [comment]
Ок, жду лог,
у меня на приставке Android и на OpenELEC(PC платформе) все работает.

**Comment by xbmcrepo** [comment]
Антон!
Воистину чудны дела .
На андроиде вечером активировался script.torrent.ts 3.0.6 и заработало хоть под айсстримом, хоть под  script.module.torrent2http

А вот на опенэлеке брыкается. Для проверки запустил Т orrent-tv.ru официальный - работает под айсстрим.
А LostFilm.TV  - не хочет запускаться. Переустановил опенэлек другую сборку через апдейт.

Сборка openelec 6.0  Nvidia_Legacy X86-64 , от 23.07.2015. Kodi-15.0-Release из официального гита xbmc. С поддержкой ACEStream и LibTorrent-Rasterbar-0.16.19  (Сборка для старых видеокарт Nvidia и Nvidia-ION)

Хотя в принципе предыдущая официальная с  Т orrent-tv.ru под айсстримом работала(ТВ смотрю иногда).

Переустановка ничего не дала. Не запускается видео в плагине. С авторизацией вопрос самоустранился после ребута.

Лог в студию  http://paste.ubuntu.com/12698257/


>Вторник,  6 октября 2015, 0:15 -07:00 от Anton Argirov <notifications@github.com>:
>
>Ок, жду лог,
>у меня на приставке Android и на OpenELEC(PC платформе) все работает.
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax

**Comment by anteo** [comment]
Владимир,

Предлагаю создать задачу непосредственно в репозитории плагина:
https://github.com/anteo/plugin.video.lostfilm.tv/issues
- это что касаемо работы плагина под неофициальной сборкой openelec 6.0  Nvidia_Legacy X86-64. Последующие задачи предлагаю создавать там же.
Вообще, работа плагина не зависит от наличия script.torrent.ts, т.к. у меня плагин общается с AceStream напрямую.
Конкретно в данном случае я вижу:
```
17:18:11 T:139992067196672  NOTICE: [support.abstract.scraper] Fetching URL http://www.lostfilm.tv/nrdr.php with params {u'c': 252, u'e': 6, u's': 1} taken: 0.163923 seconds
17:18:11 T:139992067196672  NOTICE: [support.abstract.scraper] Parsing torrent links started...
17:18:11 T:139992067196672  NOTICE: [support.abstract.scraper] Got 0 link(s) successfully
17:18:11 T:139992067196672  NOTICE: [support.abstract.scraper] []
```
- это и является проблемой (0 ссылок получено), значит как-то не так парсится страница.
Причем на официальном OpenELEC последней версии у меня все работает (проверял сегодня)
Буду очень признателен, если Вы поможете мне получить Вашу сборку OpenELEC, т.к. сам я не хочу тратить время на самостоятельную сборку.

Буквально сегодня также случилась другая проблема - китайский прокси, через который я обхожу закрытые на территории России сериалы, перестал работать, и открытие плагина сейчас происходит с ошибкой (из-за сериала "Родина", id 161). Я сейчас по этой проблеме создам новую задачу и попытаюсь решить проблему каким-нибудь автоматическим способом подбора прокси.

**Comment by xbmcrepo** [comment]
Антон!
С официальной сборкой тот же случай.
Последний лог делал на этой сборке :

https://yadi.sk/d/a5xBkqZhi7CK7
взято из форума
http://xbmc.ru/forum/showpost.php?p=57575&postcount=5
Ну а первый крэш был на сборке с этого сайта :

http://openelec.tv/get-openelec


>Среда,  7 октября 2015, 0:08 -07:00 от Anton Argirov <notifications@github.com>:
>
>Владимир,
>Предлагаю создать задачу непосредственно в репозитории плагина:
>https://github.com/anteo/plugin.video.lostfilm.tv/issues
>*  это что касаемо работы плагина под неофициальной сборкой openelec 6.0  Nvidia_Legacy X86-64. Последующие задачи предлагаю создавать там же.
Вообще, работа плагина не зависит от наличия script.torrent.ts, т.к. у меня плагин общается с AceStream напрямую.
Конкретно в данном случае я вижу:
>17:18:11 T:139992067196672  NOTICE: [support.abstract.scraper] Fetching URL http://www.lostfilm.tv/nrdr.php with params {u'c': 252, u'e': 6, u's': 1} taken: 0.163923 seconds
17:18:11 T:139992067196672  NOTICE: [support.abstract.scraper] Parsing torrent links started...
17:18:11 T:139992067196672  NOTICE: [support.abstract.scraper] Got 0 link(s) successfully
17:18:11 T:139992067196672  NOTICE: [support.abstract.scraper] []
>*  это и является проблемой (0 ссылок получено), значит как-то не так парсится страница.
Причем на официальном OpenELEC последней версии у меня все работает (проверял сегодня)
Буду очень признателен, если Вы поможете мне получить Вашу сборку OpenELEC, т.к. сам я не хочу тратить время на самостоятельную сборку.
>Буквально сегодня также случилась другая проблема - китайский прокси, через который я обхожу закрытые на территории России сериалы, перестал работать, и открытие плагина сейчас происходит с ошибкой (из-за сериала "Родина", id 161). Я сейчас по этой проблеме создам новую задачу и попытаюсь решить проблему каким-нибудь автоматическим способом подбора прокси.
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax

**Comment by anteo** [comment]
Сделал кое-какие изменения, 0.0.6 (с автоматическим выбором прокси) у меня работает на всех подопытных устройствах.

**Comment by xbmcrepo** [comment]
Антон, спасибо.
Правда уже месяц не до кино.
Проектами завалили.
Строитель ленивый пошёл, просят за него свой моск сломать.
Вот и сижу до ночи.
Сейчас в комнату с неттопом перебирусь к опенэлеку, опробую.


>Пятница, 16 октября 2015, 2:15 -07:00 от Anton Argirov <notifications@github.com>:
>
>Сделал кое-какие изменения, 0.0.6 (с автоматическим выбором прокси) у меня работает на всех подопытных устройствах.
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax

**Comment by xbmcrepo** [comment]
Антон, Вы в курсе, что Ваш репозиторий уже прописан в международном архиве аддонов для ТВ?
http://addons.tvaddons.ag/repository/russiananteo/


>Пятница, 16 октября 2015, 2:15 -07:00 от Anton Argirov <notifications@github.com>:
>
>Сделал кое-какие изменения, 0.0.6 (с автоматическим выбором прокси) у меня работает на всех подопытных устройствах.
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax

**Comment by xbmcrepo** [comment]
Антон!
Гонял на разных осях. Всё работает стабильно , виндовс, андроид, опенэлек - никто не брыкается. 


>Пятница, 16 октября 2015, 2:15 -07:00 от Anton Argirov <notifications@github.com>:
>
>Сделал кое-какие изменения, 0.0.6 (с автоматическим выбором прокси) у меня работает на всех подопытных устройствах.
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax

**Comment by xbmcrepo** [comment]
Антон!
Что-то не так пошло. При чистой установке 0.0.6 в убунту/коди 15.2, плагин не устанавливается без зависимостей - в частности в Вашем репо нет script.module.requests-2.7.0. Новая версия скрипта 2.8.1.
При установке из zip - пишет на неправильную структуру заполнения аддона.
Странно, сразу после обновления до 0.0.6 аддон устанавливался без проблем. Может быть из-за наличия предустановленных с другими аддонами скриптов .


>Пятница, 16 октября 2015, 2:15 -07:00 от Anton Argirov <notifications@github.com>:
>
>Сделал кое-какие изменения, 0.0.6 (с автоматическим выбором прокси) у меня работает на всех подопытных устройствах.
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax

**Comment by xbmcrepo** [comment]
кое-что подправил. после установки из script.module.torrent2http-0.0.9.zip аддон 0.0.6 устанавливается. Из репо - нет.
корректированный addon.xml :
https://cloud.mail.ru/public/5ytA/DrFkfJNxh


>Пятница, 16 октября 2015, 2:15 -07:00 от Anton Argirov <notifications@github.com>:
>
>Сделал кое-какие изменения, 0.0.6 (с автоматическим выбором прокси) у меня работает на всех подопытных устройствах.
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax

**Comment by anteo** [comment]
Версия script.module.requests тут не при чем, т.к. в addon.xml указывается минимальная необходимая версия. У меня на чистый Kodi 15.2 (Mac OS X, OpenELEC, Android) через репозиторий все ставится нормально. Возможно, какой-то глюк в конкретном данном случае, либо глюк, связанный с Ubuntu Kodi

**Comment by xbmcrepo** [comment]
Антон, это был глюк. Удалил в домашнем весь каталог .kodi  и всё нормализовалось. Чем больше экспериментов с установкой/переустановкой коди, тем больше вероятность глюка. Извините за ложную тревогу. 


>Вторник, 27 октября 2015, 11:39 -07:00 от Anton Argirov <notifications@github.com>:
>
>Версия script.module.requests тут не при чем, т.к. в addon.xml указывается минимальная необходимая версия. У меня на чистый Kodi 15.2 (Mac OS X, OpenELEC, Android) через репозиторий все ставится нормально. Возможно, какой-то глюк в конкретном данном случае, либо глюк, связанный с Ubuntu Kodi
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax

**Comment by xbmcrepo** [comment]
Антон!
Здесь перец выложил рабочую версию Вашего плагина. Не вдавался в подробности что он там сделал с авторизацией, но это работает :
https://github.com/cyberalexca/plugin.video.lostfilm.tv


>Вторник, 27 октября 2015, 11:39 -07:00 от Anton Argirov <notifications@github.com>:
>
>Версия script.module.requests тут не при чем, т.к. в addon.xml указывается минимальная необходимая версия. У меня на чистый Kodi 15.2 (Mac OS X, OpenELEC, Android) через репозиторий все ставится нормально. Возможно, какой-то глюк в конкретном данном случае, либо глюк, связанный с Ubuntu Kodi
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax

**Comment by cyberalexca** [comment]
За перца спасибо :)

**Comment by xbmcrepo** [comment]
В хорошем понимании этого слова

**Comment by cyberalexca** [comment]
Да я то понял :) ФИк я делал на коленке, потому что супруга фильму смотреть хотела.

Кстати, у кого нить получается юзать этот плагин с AceStream ? У меня Amazon Fire TV запускается скачка, потом что-то думает и всё. МОжет можно гдето размер буфера изменить. или еще что твикнуть.
